version: 2.1 # Use version 2.1 to enable Orb usage.

orbs:
  win: circleci/windows@5.0 # The Windows orb gives you everything you need to start using the Windows executor.

jobs:
  win_build:
    executor:
      name: win/default
      size: xlarge

    steps:
      - checkout
      - run: ./.circleci/install_dependencies_win.ps1
      - run: npm ci
      - run: npm run bootstrap
      - run: npm run build -- --target=debug
      - run: npm run build -- --target=release
      - run: npm run package -- --target=debug
      - run: npm run package -- --target=release

  nix_build:
    machine:
      image: ubuntu-2004:current
    resource_class: xlarge
    steps:
      - checkout
      - run: npm ci
      - run: npm run bootstrap
      - run: chmod a+x ./.circleci/install_dependencies_nix.sh
      - run: ./.circleci/install_dependencies_nix.sh
      - run: npm run build -- --target=debug
      - run: npm run build -- --target=release
      - run: npm run package -- --target=debug
      - run: npm run package -- --target=release

  mac_intel_build:
    macos:
      xcode: 14.2.0
    resource_class: large
    steps:
      - checkout
      - run: npm ci
      - run: npm run bootstrap
      - run: chmod a+x ./.circleci/install_dependencies_nix.sh
      - run: ./.circleci/install_dependencies_nix.sh
      - run: npm run build -- --target=debug
      - run: npm run build -- --target=release
      - run: npm run package -- --target=debug
      - run: npm run package -- --target=release

  mac_arm_build:
    macos:
      xcode: 14.2.0
    resource_class: large
    steps:
      - checkout
      - run: npm ci
      - run: npm run bootstrap
      - run: chmod a+x ./.circleci/install_dependencies_nix.sh
      - run: ./.circleci/install_dependencies_nix.sh
      - run: npm run build -- --target=debug --arch=arm
      - run: npm run build -- --target=release --arch=arm
      - run: npm run package -- --target=debug
      - run: npm run package -- --target=release

workflows:
  full_build:
    jobs:
      - win_build
      - nix_build
      - mac_intel_build
      - mac_arm_build
