version: 2.1 # Use version 2.1 to enable Orb usage.

orbs:
  win: circleci/windows@5.0 # The Windows orb gives you everything you need to start using the Windows executor.

jobs:
  win_build:
    executor:
      name: win/default
      size: xlarge

    steps:
      - checkout
      - run: ./.circleci/install_dependencies_win.ps1
      - run: npm ci
      - run: npm run bootstrap
      - run: npm run build -- --target=debug
      - run: npm run build -- --target=release
      - run: npm run package -- --target=debug
      - run: npm run package -- --target=release
      - store_artifacts:
          path: ./vendor/webrtc/out/win_x64_debug
          destination: win_x64_debug
      - store_artifacts:
          path: ./vendor/webrtc/out/win_x64_release
          destination: win_x64_release

  nix_build:
    machine:
      image: ubuntu-2004:current
    resource_class: xlarge
    steps:
      - checkout
      - run: npm ci
      - run: npm run bootstrap
      - run: chmod a+x ./.circleci/install_dependencies_nix.sh
      - run: ./.circleci/install_dependencies_nix.sh
      - run: npm run build -- --target=debug
      - run: npm run build -- --target=release
      - run: npm run package -- --target=debug
      - run: npm run package -- --target=release
      - store_artifacts:
          path: ./vendor/webrtc/out/linux_x64_debug
          destination: linux_x64_debug
      - store_artifacts:
          path: ./vendor/webrtc/out/linux_x64_release
          destination: linux_x64_release

  mac_intel_build:
    macos:
      # To give us 100GB of disk
      xcode: 12.5.1
    resource_class: medium
    steps:
      - checkout
      - run: npm ci
      - run:
          no_output_timeout: 30m
          command: npm run bootstrap
      - run: npm run build -- --target=debug
      - run: npm run build -- --target=release
      - run: npm run package -- --target=debug
      - run: npm run package -- --target=release
      - store_artifacts:
          path: ./vendor/webrtc/out/mac_x64_debug
          destination: mac_x64_debug
      - store_artifacts:
          path: ./vendor/webrtc/out/mac_x64_release
          destination: mac_x64_release

  mac_arm_build:
    macos:
      # To give us 100GB of disk
      xcode: 12.5.1
    resource_class: medium
    steps:
      - checkout
      - run: npm ci
      - run:
          no_output_timeout: 30m
          command: npm run bootstrap
      - run: npm run build -- --target=debug --arch=arm64
      - run: npm run build -- --target=release --arch=arm64
      - run: npm run package -- --target=debug --arch=arm64
      - run: npm run package -- --target=release --arch=arm64
      - store_artifacts:
          path: ./vendor/webrtc/out/mac_arm64_debug
          destination: mac_arm64_debug
      - store_artifacts:
          path: ./vendor/webrtc/out/mac_arm64_release
          destination: mac_arm64_release

workflows:
  full_build:
    jobs:
      - win_build
      - nix_build
      - mac_intel_build
      - mac_arm_build
