name: Check WebRTC Releases
on:
  schedule:
  - cron: "0 12 * * 6"
  workflow_dispatch:
  
jobs:
  check_releases:
    runs-on: ubuntu-latest
    steps:
      - name: get_webrtc_version
        run: |
          WEBRTC_VERSION=$(npm run scripts:latest_release)
          echo $WEBRTC_VERSION
          echo version=$WEBRTC_VERSION >> $GITHUB_OUTPUT
      - run: echo ${{ steps.get_webrtc_version.outputs.version }}
      - name: get_latest_build
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          owner: bengreenier
          repo: webrtc
          excludes: prerelease, draft
      - run: echo ${{ steps.get_latest_build.outputs.id }}
      - name: version_comparision
        run: |
          echo should_build=false >> $GITHUB_OUTPUT
      - uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        if: ${{ steps.version_comparision.outputs.should_build }}
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
